apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx-l:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - mountPath: /var/www/html  # Cả Nginx và PHP-FPM phải cùng mount tới đường dẫn này
          #     name: app-volume

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  ports:
    - protocol: TCP
      port: 80
