apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      enableServiceLinks: false
      containers:
        - name: php
          image: php-l:latest
          imagePullPolicy: Never
      #     volumeMounts:
      #       - mountPath: /var/www/storage/logs
      #         name: storage-logs
      #       - mountPath:  /var/www/html
      #         name: app-volume
      # volumes:
      #   - name: storage-logs
      #     persistentVolumeClaim:
      #       claimName: storage-logs-pvc
      #   - name: app-volume
      #     hostPath:
      #       path: /Users/yoochan/Documents/k8s/demo-k8s

---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
