apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0  # secret
  MYSQL_DATABASE: ZGVtby1teXNxbA==  # demo-mysql
  MYSQL_USER: cm9vdA==   # root
  MYSQL_PASSWORD: c2VjcmV0
